        NUMPY

    Numpy:- Numpy is a python library that provides an array-based dataStructure for performing fast calculations  with numeric data


In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.3'

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
arr= np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
type(my_list)

list

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [10]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.arange(20, 10). #empty array, bec starting from 20 and end from 10 not possible

array([], dtype=int64)

In [15]:
np.arange(-20, 10) #starting value:- -20, end value:- 10, step value=1

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.zeros(5) #Make an array

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros([2,2], dtype=int) 

array([[0, 0],
       [0, 0]])